# workflow name
name: Hello World!
# trigger event
on: push

jobs:
  # job id. must be unique
  build:
      # job name
      name: Greeting
      # runtime machine
      runs-on: ubuntu-latest
      steps:
        - run: echo "Hello World"