name: Notify Slack
on:
  push:
    branches:
      - master
jobs:
  notify:
    # https://github.community/t5/GitHub-Actions/Triggering-workflow-on-merge/td-p/40930
    # https://qiita.com/osakiy/items/df80db383ce33b82c797
    # https://developer.github.com/webhooks/event-payloads/
    # https://developer.github.com/webhooks/event-payloads/#pull_request
    # https://github.com/marketplace/actions/post-slack-message
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack-channel: CT66WM0R4
          slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}" 🤓
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"